name: Python application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r starter/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 starter --count --max-line-length=120 --statistics

      - name: Test with pytest (ML pipeline)
        run: |
          cd starter/starter
          pytest -v test_ml.py

      - name: Test with pytest (API)
        run: |
          cd starter
          pytest -v test_main.py
